apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: echo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: For the echo application.
  sourceRepos:
    - https://github.com/yarsiemanym/echo.git
  destinations:
    - namespace: echo
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: echo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/yarsiemanym/echo.git
    targetRevision: HEAD
    path: manifests
    directory: 
      exclude: argocd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: echo